### ISSUE TITLE
Borked in production

### ISSUE THREAD

**Issue by pezholio** [theodi/forkbomb#51]
From the Heroku logs - WAT. Looks like the migrations haven't run, or... Something:

```
2013-12-19T17:28:24.167183+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "users" does not exist
2013-12-19T17:28:24.167185+00:00 app[web.1]: LINE 1: SELECT  "users".* FROM "users"  WHERE "users"."provider" = '...
2013-12-19T17:28:24.167187+00:00 app[web.1]:                                ^
2013-12-19T17:28:24.167189+00:00 app[web.1]: : SELECT  "users".* FROM "users"  WHERE "users"."provider" = 'github' AND "users"."uid" = '109774'  ORDER BY "users"."id" ASC LIMIT 1
2013-12-19T17:28:24.167193+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "users" does not exist
2013-12-19T17:28:24.167194+00:00 app[web.1]: LINE 1: SELECT  "users".* FROM "users"  WHERE "users"."provider" = '...
2013-12-19T17:28:24.167195+00:00 app[web.1]:                                ^
2013-12-19T17:28:24.167197+00:00 app[web.1]: : SELECT  "users".* FROM "users"  WHERE "users"."provider" = 'github' AND "users"."uid" = '109774'  ORDER BY "users"."id" ASC LIMIT 1
2013-12-19T17:28:24.167278+00:00 app[web.1]: Completed 500 Internal Server Error in 3ms
2013-12-19T17:28:24.167296+00:00 app[web.1]: Completed 500 Internal Server Error in 3ms
2013-12-19T17:28:24.168492+00:00 app[web.1]: 
2013-12-19T17:28:24.168494+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2013-12-19T17:28:24.168496+00:00 app[web.1]: LINE 1: SELECT  "users".* FROM "users"  WHERE "users"."provider" = '...
2013-12-19T17:28:24.168497+00:00 app[web.1]:                                ^
2013-12-19T17:28:24.168499+00:00 app[web.1]: : SELECT  "users".* FROM "users"  WHERE "users"."provider" = 'github' AND "users"."uid" = '109774'  ORDER BY "users"."id" ASC LIMIT 1):
2013-12-19T17:28:24.168500+00:00 app[web.1]:   app/models/user.rb:8:in `find_for_github_oauth'
2013-12-19T17:28:24.168502+00:00 app[web.1]:   app/controllers/users/omniauth_callbacks_controller.rb:4:in `github'
2013-12-19T17:28:24.168503+00:00 app[web.1]: 
2013-12-19T17:28:24.168504+00:00 app[web.1]: 
2013-12-19T17:28:24.168508+00:00 app[web.1]: 
2013-12-19T17:28:24.168509+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2013-12-19T17:28:24.168511+00:00 app[web.1]: LINE 1: SELECT  "users".* FROM "users"  WHERE "users"."provider" = '...
2013-12-19T17:28:24.168512+00:00 app[web.1]:                                ^
2013-12-19T17:28:24.168513+00:00 app[web.1]: : SELECT  "users".* FROM "users"  WHERE "users"."provider" = 'github' AND "users"."uid" = '109774'  ORDER BY "users"."id" ASC LIMIT 1):
2013-12-19T17:28:24.168515+00:00 app[web.1]:   app/models/user.rb:8:in `find_for_github_oauth'
2013-12-19T17:28:24.168517+00:00 app[web.1]:   app/controllers/users/omniauth_callbacks_controller.rb:4:in `github'
2013-12-19T17:28:24.168518+00:00 app[web.1]: 
2013-12-19T17:28:24.168519+00:00 app[web.1]: 
```

**Comment by thatosmk** [comment]
How did you solve this?

**Comment by thatosmk** [comment]
nevermind, figured out what the problem was.

**Comment by Floppy** [comment]
@thatosmk good for you, well done 😄  🎉
